before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - export CCACHE_DIR=/dev/shm/my-ccache-in-memory
  - export CCACHE_NOCOMPRESS=1
  - df -h /dev/shm
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"
  - . version.sh && echo $BRANCH

build-debian-12-amd64:
  image: robertcnelson/beagle-devscripts-kernel-debian-12-amd64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-12-amd64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-amd64
  stage: build
  script:
    - tar --zstd -xf ccache.tar.zst -C / || true
    - df -h /dev/shm
    - ccache -M 5G
    - ccache -sv
    - ccache --recompress=uncompressed
    - ccache -z
    - cp -v system.sh.gitlab system.sh
    - ./build_deb.sh
    - du -sh deploy/linux-image-*.deb || exit 1
    - ccache -sv
    - df -h /dev/shm
    - tar --use-compress-program='zstd -9' -cf ccache.tar.zst /dev/shm/my-ccache-in-memory
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  artifacts:
    expire_in: 1 week
    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-12-$CI_JOB_ID"
    paths:
      - "deploy/linux-image-*.deb"

build-debian-13-amd64:
  image: robertcnelson/beagle-devscripts-kernel-debian-13-amd64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-13-amd64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-amd64
  stage: build
  script:
    - tar --zstd -xf ccache.tar.zst -C / || true
    - df -h /dev/shm
    - ccache -M 5G
    - ccache -sv
    - ccache --recompress=uncompressed
    - ccache -z
    - cp -v system.sh.gitlab system.sh
    - ./build_deb.sh
    - du -sh deploy/linux-image-*.deb || exit 1
    - ccache -sv
    - df -h /dev/shm
    - tar --use-compress-program='zstd -9' -cf ccache.tar.zst /dev/shm/my-ccache-in-memory
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  artifacts:
    expire_in: 1 week
    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-13-$CI_JOB_ID"
    paths:
      - "deploy/linux-image-*.deb"

build-debian-14-amd64:
  image: robertcnelson/beagle-devscripts-kernel-debian-14-amd64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-14-amd64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-amd64
  stage: build
  script:
    - echo "Acquire::http::Proxy \"http://192.168.1.10:3142\";" > /etc/apt/apt.conf.d/00aptproxy
    - apt-get update
    - apt-get dist-upgrade -yq
    - tar --zstd -xf ccache.tar.zst -C / || true
    - df -h /dev/shm
    - ccache -M 5G
    - ccache -sv
    - ccache --recompress=uncompressed
    - ccache -z
    - cp -v system.sh.gitlab system.sh
    - ./build_deb.sh
    - du -sh deploy/linux-image-*.deb || exit 1
    - ccache -sv
    - df -h /dev/shm
    - tar --use-compress-program='zstd -9' -cf ccache.tar.zst /dev/shm/my-ccache-in-memory
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  artifacts:
    expire_in: 1 week
    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-14-$CI_JOB_ID"
    paths:
      - "deploy/linux-image-*.deb"
